Add Supporting Tools to API[KEH-368]
ONS-Innovation/keh-tech-audit-tool-api pull request #8
Opened 2024-12-18 08:39 UTC by delterr

2024-12-18 14:42 UTC, evisos-ons commented on README.md
> +      "project_tracking_toolsf": [
spelling

2024-12-18 15:07 UTC, delterr commented on README.md
> +      "project_tracking_toolsf": [
> spelling

😿 
Fixed

2024-12-30 09:43 UTC, evisos-ons requested changes
Needs update to MkDocs

2024-12-30 09:43 UTC, evisos-ons commented on aws_lambda_script/app/resources.py
> +            or "supporting_tools" not in new_project
so supporting_tools needs to be in the payload but each entry within supporting_tools can be empty. I presume that's okay? Meaning it's not mandatory.

2025-01-03 09:12 UTC, evisos-ons reviewed
Should update docs for new API schema.

2025-01-03 18:23 UTC, delterr commented on aws_lambda_script/app/resources.py
> +            or "supporting_tools" not in new_project
Well if supporting tools is in the payload it probably also means theres also the other bits of data that come under it

2025-01-03 18:24 UTC, delterr commented
> Should update docs for new API schema.

I can't seem to updae the docs, and the way the JSON is represented right now doesn't look maintainable. We should discuss this on Monday...

2025-01-06 11:11 UTC, evisos-ons reviewed
Tiny comments, but all else looks good. Terraform doesn't need touching as well which is good.

Once we've approved PR we can look to deploy.

2025-01-06 11:11 UTC, evisos-ons commented on README.md
> +    }
Uses {main: , others: } right?

2025-01-06 11:11 UTC, evisos-ons commented on docs/endpoints/project.md
> +        "project_tracking_tools": "strings",
string or strings?

2025-01-06 11:11 UTC, evisos-ons commented on docs/endpoints/projects.md
> +      "project_tracking_tools": "strings",
string or strings?

2025-01-06 11:31 UTC, evisos-ons commented
The buckets have `array_data.json` in. Maybe, update the `-testing` bucket to have the same data too as right now they're different.

I think we should be removing the bracketed part of some of the entries to less complicate the data when autocompleting. For example: "Confluence **(integrated with Jira)**"

2025-01-08 11:55 UTC, merged